# Site settings
title: Welcome!
email: nick@nrebhun.com
description: > # this means to ignore newlines until "baseurl:"
 Thank you for visiting my site! Currently, this is under some serious construction while I teach myself
 how to properly utilize Jekyll, Markdown, and GitHub Pages!
 I encourage you to check out my Projects page, to see some of the stuff I'm working / have worked on!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nrebhun.com" # the base hostname & protocol for your site
twitter_username: nrfactor
github_username:  nrebhun

# Build settings
markdown: kramdown
