# Site settings
title: Super Catchy Title!
email: nrfactor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Welcome to my website! This is currently under some serious construction while I teach myself how to properly utilize Jekyll, Markdown, and Github Pages... so pardon our dust!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nickrebhun.com" # the base hostname & protocol for your site
twitter_username: nrfactor
github_username:  nrfactor

# Build settings
markdown: kramdown
