# Site settings
title: "Welcome, traveler!"
home_title: "Home"
contact_me: "Contact:"
email: nick@nrebhun.com
description: >
 Thanks for visiting my site!
 I encourage you to check out my Projects page, to see some of the stuff I'm working / have worked on!
baseurl: ""
url: "http://www.nrebhun.com"
twitter_username: nrebhun_
github_username:  nrebhun

# Build settings
markdown: kramdown
